---
title: "to fix"
author: "Michiel van Dijk"
date: "10/19/2020"
output: pdf_document
---

# Create own universe for packages
#https://www.r-bloggers.com/2021/06/how-to-create-your-personal-cran-like-repository-on-r-universe/

# Documentation
- replace_gaez: Not sure if it is documented that suitability which are zero need to be replaced

# Functions
- replace_gaez: At the moment when a suitability or py is zero for an adm and no replacement crop is stated in replace_gaez.csv it returns an error. Need to add message and to set fixed replacements. Also perhaps develop a function that analyzes all areas and indicates where gaez replace needs to be set.

- run_spam(): If combine_inputs() is not run it returns an error. Probably all functions return an error if the previous step is not run. Proper error warnings should be added

- view_stack("rice", var = "ha", param) does not work for GMB. Unknow error

- view_panel() does not work. Perhaps discard.

- split_scores/split_priors: I added a statement that rur_pop_share = 0 if it is NA. NAs are caused by missing values in bs (example for ET02). I suspect it has to do with the sampling of GAEZ to 30sec where edge information might be lost if it is resampled to a finer grid (e.g. 30 sec).

# MWI, GMB examples
- select_sasam: Error in input file path. Corrected in GMB only
- run all spatial: when the location of the scripts changes to a year folder such as in the case of GMB, one has to change all the paths. Perhaps this can be improved.

# GAMS treatment
- I know use gams path before gams.exe. Probably smaller to put it into igdx




# Additions
## Intertemporally linked cropmaps

- I added prepare cropland_tp1 to link results_tp1 with cropland extent. This is a temporary fix. Note that "results_tp1" was added to the load_data function to make this possible. Also the data that is loaded does not specifiy the type of model used but I am not sure if this is necessary.

## Other
- Function that harmonizes ha with FAOSTAT

- Option to have a raw_path for global files but country path for subnational statististics. Convenient if multiple countries need to be done. In fact the raw path is not used anywhere inside the functions as the code to process maps and statistics is not capture in function. Hence, we could simply add the possibility to set a global path and use param$glob_path when global maps are called. In this way, the user can decide either split the location of the raw  data or set glob_path to raw_path (default if is.null(glob_path))

- Function that reports slack variables from gdx output

- Check if there are no NA or -999 values at top level when running at ADM1. Yating had this for ETH and this resulted in an error.

- Use other production systems for same crop as replacement when suitability is missing. E.g. currently I am using maiz_I for sunf_I if sunf_I is missing as defined in gaez_replace. Might be better to use sunf_S. 

- Add an approach to run all steps for a single ADM1 if the model is run at ADM1. All lower level functions in fact do this but they are not exported. Need to create standardized names (e.g. run_model vs run_model_adm) for all functions, export and document them. 

- Things go wrong with the GAEZ data at 30 sec because grid cells that are located at the border are NA because of the coarser resolution. Problem is caused by clipping the 5 arcmin to the country polygon. In this process 5 arcmin grid cells which centre is located outside the country are not selected. If we would first disaggregate the global GAEZ maps and then clip. Many more 30sec border cells will be retained. Need to do the same thing for GMIA!

- Note that for ET6 there is an error in split_scores/priors because all rev values are NA (and hence 0). Possible introduce a warning when all GAEZ values are zero within an ADM1. At the moment we only check if GAEZ is 0 for the whole country.

- Add adm_code to pdf file with adm maps.

- Add check to see if adm_code etc in poly and adm_list add up

- Add check if file exists before running harmonization. For example if GAEZ PY is not created there is no check and an error will occur.

- note that an adm2_code is missing in the ZWE model but it still runs. Need to check how this plays out and add warning when this occurs.
