---
title: "Country examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Country examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  bib/mapspamc.bib
bibliography: bib/mapspamc.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`mapspamc` is accompanied by several country examples to illustrate the workings of the package. The examples provide fully developed scripts to run `mapspamc` from start to finish and may serve as a starting point or even template for users, who want to prepare their own country case-studies. The examples are stored in Github repositories using the following naming convention:  github.com/michielvandijk/mapspamc_iso3c, where 'iso3c' is the [ISO 3166-1 alpha-3 letter](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) country code in lowercase. At the moment two examples are provided: [mapspamc_mwi](https://github.com/michielvandijk/mapspamc_mwi) for Malawi and [mapspamc_eth](https://github.com/michielvandijk/mapspamc_eth) for Ethiopia. We hope that users will add their work as additional examples.

# Preparing the country examples

- Install all required [software](installation.html).
- Visit the GitHub country example repository and click on 'clone or download' to copy the repository to your machine.
- Open the project with RStudio.
- Update the location of the model and the mapspamc database in the 01_model_setup.r script so it matches with the locations on your machine. 
- Copy the [mapspamc database](@ADD) to the set location on your machine.

Now you should be ready to run the country example on your own machine! The articles in the Running `mapspamc` section will guide you through the various steps to build the model, using the Malawi example.

