---
title: "Crop distribution maps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Crop distribution maps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  bib/mapspamc.bib
bibliography: bib/mapspamc.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Comprehensive, detailed and spatially explicit information on the locations of crops is essential to inform agricultural and food policies. crop distribution maps are used to as crucial input for regional crop monitoring systems [@Fritz2019; @Becker-Reshef2019], to analyse national irrigation potential [@You2014a; @Xie2017] and to assess the impact of climate change and socioeconomic development on land use change and wider developmental trade-offs [@Ahmed2016].

Currently, only several global products provide spatial information on the location of crops [@Monfreda2008; @Portmann2010; @You2014a; see @Anderson2015 for a comparison]. These datasets use spatial information on land cover, suitability and irrigation to 'pixelate' (sub)national agricultural statistics at 5 arc minute resolution (~10x10 kilometer at the equator). Apart from the Spatial Production Allocation Model (SPAM), which latest version covers the year 2010 [@Yu2020], these datasets are rather outdated.

Global crop distribution maps are a useful starting point for national analysis but are of limited use when more detailed and up to date information is required. National decision makers often want to zoom in on subnational regions (e.g. bread basket areas), which requires (higher) resolution maps that are consistent with national data sources such as land cover maps and subnational crop statistics.  

An interesting alternative and new approach to create high resolution crop distribution maps are machine learning techniques, which can be used to identify the location of specific crops using satellite imagery in combination with other predictors. Although promising, these techniques are still under active development and the available studies predominantly target large-scale crops (e.g. soy bean and palm oil), which are easier to identify using machine learning classification approaches [@Zhong2016; @Song2017; @Danylo2020]. 

`mapspamc` provides the infrastructure to create plausible spatial estimates of physical and harvested crop area at national scale using the SPAM approach described in @You2006, @You2009, @You2014a and @Yu2020, which uses a cross-entropy framework to allocate subnational land use information on a 5 arc minute  grid. Apart from the standard model, `mapspamc` offers an alternative algorithm, which makes it possible to create crop distributions maps with a resolution of 30 arc second (~1x1 kilometer at the equator) - see @VanDijk2022b for more information.^[Note `mapspamc` does not support all the model extensions presented in @VanDijk2022b. At the moment, it is not possible to blend in detailed information on the location of crops (e.g. OpenStreetMap information, large-farm surveys and machine learning products). `mapspamc` also does not include the approach to backcast crop distribution maps to earlier periods. These features might be added in an futured updates.]
  

## References
