---
title: "Input data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  bib/mapspam.bib
bibliography: bib/mapspam.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Crop statistics

The aim of SPAMc is to spatially allocate national and subnational information on harvested and physical crop area for four different farming systems (subsistence, low-input, high-input and irrigated). The use of subnational statistics is of key importance and greatly improves the quality of the gridded maps [@Joglekar2019]. In the ideal situation, crop and farming system information at three administrative area levels would be available: national level (level 0), state or provincial level (level 1) and district, county or department level (level 2). In practice, this is almost never the case and assumptions need to be made to [prepare the data](process_subnational_statistics.html).

Information on harvested area at the national level can be obtained from [FAOSTAT](http://www.fao.org/faostat/en/#home), while data on irrigated crop area can be obtained from [AQUASTAT](http://www.fao.org/nr/water/aquastat/data/query/index.html?lang=en).  Unfortunately, most of the other data is not easily available and needs to be collected by exploring a variety of sources (see [Input data collection](input_data_collection.html)).


## Cropland extent

To allocate the physical area statistics SPAMc requires a cropland extent, which shows the location of cropland in a country for the target year. There are several global cropland products and often countries produce their own land cover map, which includes a cropland class. Comparison between different cropland sources, shows a lot of variation and often disagreement [@ADD]. To account for the uncertainty in the location of cropland, @ADD combined several different products into one so-called synergy (or synergistic) cropland map. A more recent product was prepared by @Lu2020 and used as input for the construction of SPAM2010.

The synergy cropland approach combines all available (global) cropland maps and creates a ranking for each grid cell that measures the level of agreement between the products. In the SPAMc data-preparation stage, the grid cells with the least uncertainty are selected first when allocating physical area of individual crops. Apart from the ranking, the synergy cropland approach also creates maps with the medium and maximum cropland area per grid cell. The medium area product is used as the base layer by SPAMc but in case this is not sufficient to allocate all the physical area, grid cells from the maximum cropland map can be used (see [Combine input data](combine_input_data.html) for more information on how this is done).  

## Irrigation

To allocate the irrigated crops, SPAMc needs an irrigated area extent. Similar to the synergy cropland map, we create a synergy irrigated area map that takes into account the uncertainties related to the location of irrigated areas. At present, there are only two global products that provide this information. the Global Map of Irrigated Areas (GMIA) [@Siebert2013], shows the areas that are equipped for irrigation based on national survey data and maps for 2005 at 5 arcmin. The Global Irrigated Areas (GIA) map [@Meier2018] depicts actual irrigated areas around the period 2005. It combines normalized difference vegetation index (NDVI) maps, crop suitability data and information on the location of areas equipped for irrigation to create an irrigated area map with a resolution of 30 arcsec. In comparison to the GMIA, it shows 18% more irrigated area globally.


## Biophysical suitability and potential yield

Spatially explicit information on biophysical suitability and potential yield is taken from @IIASA2012. The International Institute for Applied Systems Analysis (IIASA) in collaboration with FAO, developed the global agro-ecological zones (GAEZ) methodology that assesses the biophysical limitations and potentials for a large number of crops across three farming systems: rainfed–low input/subsistence, rainfed–high input and Irrigated-high input. The first class is used for both the low-input and subsistence system in SPAMc. GAEZ presents spatially explicit information on the biophysical suitability (on a scale from 1 to 100) and potential yield for (in t/ha) separate for each farming system. 


## Accessibility

As a proxy for access to markets and quality of road infrastructure we use two global maps of travel time to high-density urban centers. The first map [@Nelson2008] depicts the global road infrastructure in 2000, while second map [@Weiss2018] contains information for the year 2015. Although both maps depict travel time  at a resolution of 1×1 kilometer, they cannot be regarded as time-series because the maps were created with a different definition of a city. @Nelson2008 uses travel time to the nearest city of 50,000, while @Weiss2018 uses the urban areas in the Global Human Settlement Grid of high-density land cover to locate cities. The most recent product also different source information and includes minor roads (e.g., unpaved rural roads), which were only marginally covered by the older map. We used the 2000 and 2010 global travel time maps as indicator for accessibility for the 2000 and 2010 crop distribution maps, respectively.


## Rural population density

We used the WorldPop [@Tatem2017] database as a our primary source of information for national population density. WorldPop combines a random forest model with census data to generate a gridded prediction of population density at ~100 meter spatial resolution [@Stevens2015a]. Data is available for at a number of spatial resolutions and various years. We used the global maps at 1x1 kilometer and for the period 2000 and 2010 for our analysis. 

To identify rural population areas, and similar to SPAM, we use the urban extent from GRUMP [@CIESIN2011] due to lack of other sources. Urban areas, were identified by analyzing nighttime lights in combination with information on settlement points. Rural population was selected by removing grid cells that are located within the urban extent polygons. 


## Crop price

To calculate the potential revenue of a crop at the grid cell level, we followed the SPAM approach [@Wood-Sichra2016] and multiplied the potential yield from @IIASA2012 with crop prices from @FAO2019.  



## References
