---
title: "Input data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  bib/mapspamc.bib
bibliography: bib/mapspamc.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Crop statistics

The aim of `mapspamc` is to spatially allocate national and subnational information on harvested and physical crop area for four different farming systems (subsistence, low-input rainfed, high-input rainfed and high-input irrigated). The use of subnational statistics is of key importance and greatly improves the quality of the gridded maps [@Joglekar2019]. Three types of crop statistics are required: (1) harvested ara, (2) cropping intensity and (3) farming system shares. In the ideal situation, crop and farming system information would be available at three administrative area levels: national level (level 0), state or provincial level (level 1) and district, county or department level (level 2). In practice, data is almost always incomplete, covering only a selection of crops and subnational administrative units. This is not a problem for `mapspamc` as it is designed to deal with incomplete data.

Information on harvested area at the national level can be obtained from [FAOSTAT](http://www.fao.org/faostat/en/#home), while data on irrigated crop area can be taken from [AQUASTAT](http://www.fao.org/nr/water/aquastat/data/query/index.html?lang=en).  Unfortunately, most of the other data is not easily available and needs to be collected by exploring a variety of sources (see [Input data collection](input_data_collection.html)).


## Cropland extent

To allocate the physical area statistics `mapspamc` requires a cropland extent, which shows the location of cropland in a country for the target year. There are several global cropland products and often countries produce a national land cover map, which shows the location of cropland. To account for the uncertainty in the location of cropland, @Fritz2011 combined several different products into one so-called synergy cropland map. A more recent product was prepared by @Lu2020 and used as input for the construction of SPAM2010.

The synergy cropland approach combines all available (global) cropland maps and creates a ranking for each grid cell that measures the level of agreement between the various input maps. In the `mapspamc` the grid cells with the least uncertainty are selected first when allocating physical area of individual crops. Apart from the ranking, the synergy cropland approach also prepares maps with the mean and maximum cropland area per grid cell. The mean area product is used as the base layer by `mapspamc` but in case this is not sufficient to allocate all the physical area, grid cells from the maximum cropland map can be used (see [Model preparation](model_preparation.html) for more information on how this is done).  


## Irrigation

To allocate the irrigated crops, `mapspamc` needs an irrigated area extent. Similar to the synergy cropland map, we create a synergy irrigated area map that takes into account the uncertainties related to the location of irrigated areas. At present, there are only two global products that provide this information. the Global Map of Irrigated Areas (GMIA) [@Siebert2013], shows the areas that are equipped for irrigation based on national survey data and maps for 2005 at 5 arc minutes. The Global Irrigated Areas (GIA) map [@Meier2018] depicts actual irrigated areas around the period 2005. It combines normalized difference vegetation index (NDVI) maps, crop suitability data and information on the location of areas equipped for irrigation to create an irrigated area map at a resolution of 30 arc seconds. In comparison to the GMIA, it shows 18% more irrigated area globally.


## Biophysical suitability and potential yield

Spatially explicit information on biophysical suitability and potential yield is taken from @IIASA2012. The International Institute for Applied Systems Analysis (IIASA) in collaboration with FAO, developed the global agro-ecological zones (GAEZ) methodology that assesses the biophysical potential for a large number of crops across three farming systems: low-input rainfed, high-input rainfed and high-input irrigated systems. The first class is used for both the subsistence and low-input system in `mapspamc`. GAEZ presents spatially explicit information on the biophysical suitability (on a scale from 1 to 100) and potential yield (in t/ha) separate for each farming system. 


## Accessibility

As a proxy for access to markets and quality of road infrastructure we used a global map with travel time to high-density urban centers. @Weiss2018 depicts the global road infrastructure in 2015 by presenting travel time to urban areas at a resolution of 1×1 kilometer.


## Rural population density

We used the WorldPop [@Tatem2017] database as a our primary source of information for national population density. WorldPop combines a random forest model with census data to generate a gridded prediction of population density at ~100 meter spatial resolution [@Stevens2015a]. Data is available for at a number of spatial resolutions and various years. We used the global maps at 1x1 kilometer as input for our analysis. To identify the rural population, we used the urban extent from @Schiavina2022. Rural population was selected by removing grid cells that are located within the urban extent. 


## Crop price

To calculate the potential revenue of a crop at the grid cell level, we followed the SPAM approach [@Wood-Sichra2016] and multiplied the potential yield from @IIASA2012 with crop prices from @FAO2019.  



## References
